# Generated by Django 5.1.3 on 2024-11-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('description', models.TextField()),
                ('author', models.CharField(default='Unknown Author', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('genre', models.CharField(max_length=50)),
                ('is_favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
