# Generated by Django 5.1.3 on 2024-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0002_alter_bookmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='pdf_file',
            field=models.FileField(upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
