# Generated by Django 5.1.3 on 2024-11-17 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('katalog', '0003_alter_bookmodel_pdf_file_alter_bookmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookmodel',
            name='page_count',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
