# Generated by Django 5.1.3 on 2024-11-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profilemodel_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default-avatar.jpg', null=True, upload_to='avatars/'),
        ),
    ]
